name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "ğŸ¤– GitHub Notifier"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          content: |
            ğŸš¨ **Novo push detectado!**
            Um novo push foi realizado no repositÃ³rio **urban-octo-engine**.
            > Mensagem de teste: Este Ã© apenas um teste de integraÃ§Ã£o com o Discord! ğŸ‰
            - Autor: ${{ github.actor }}
            - Branch: `${{ github.ref }}`
            - [Ver commit](${{ github.event.head_commit.url }})
